// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PathfinderPhotography.Data;

#nullable disable

namespace PathfinderPhotography.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115011900_AddGeminiMarketingImage")]
    partial class AddGeminiMarketingImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This matches the ApplicationDbContextModelSnapshot
            // The migration adds AiMarketingImageData to PhotoSubmissions table
        }
    }
}
